version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8081:80"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://missao.mbl.yt
      ASSET_URL: https://missao.mbl.yt
      APP_KEY: base64:9U3Kf7t0b8s5F8hC1d4k4nV7n1v3c5JqYwq4y0t6s2Q=
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
      CACHE_STORE: array
      SESSION_DRIVER: cookie
      QUEUE_CONNECTION: sync
      VIEW_COMPILED_PATH: /tmp/views
      LOG_CHANNEL: stderr
    volumes:
      - storage_data:/app/storage/app/public
      - database_data:/app/database
    restart: unless-stopped

volumes:
  storage_data:
  database_data:
